<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Home-PC" name="com.practice.testcases.HomePageTest" tests="15" failures="2" timestamp="31 Oct 2018 07:50:18 GMT" time="34.921" errors="0">
  <testcase name="verifyHomePageTitle" time="4.104" classname="com.practice.testcases.HomePageTest"/>
  <testcase name="CalendarPageTest" time="5.612" classname="com.practice.testcases.HomePageTest"/>
  <testcase name="verifyCalendarPageTitle" time="0.142" classname="com.practice.testcases.HomePageTest">
    <failure type="java.lang.AssertionError" message="expected [Administrator - Home - vtiger CRM 5 - Commercial Open Source CRM] but found [Administrator - Calendar - vtiger CRM 5 - Commercial Open Source CRM]">
      <![CDATA[java.lang.AssertionError: expected [Administrator - Home - vtiger CRM 5 - Commercial Open Source CRM] but found [Administrator - Calendar - vtiger CRM 5 - Commercial Open Source CRM]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.practice.testcases.HomePageTest.verifyCalendarPageTitle(HomePageTest.java:73)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyCalendarPageTitle -->
  <testcase name="orgPageTest" time="5.737" classname="com.practice.testcases.HomePageTest"/>
  <testcase name="verifyOrgPageTitle" time="0.094" classname="com.practice.testcases.HomePageTest"/>
  <testcase name="contactsPageTest" time="3.378" classname="com.practice.testcases.HomePageTest"/>
  <testcase name="verifyContactsPageTitle" time="0.090" classname="com.practice.testcases.HomePageTest"/>
  <testcase name="opportunitiesPageTest" time="3.521" classname="com.practice.testcases.HomePageTest"/>
  <testcase name="verifyOppoPageTitle" time="0.172" classname="com.practice.testcases.HomePageTest"/>
  <testcase name="productsPageTest" time="3.307" classname="com.practice.testcases.HomePageTest"/>
  <testcase name="verifyProductsPageTitle" time="0.078" classname="com.practice.testcases.HomePageTest"/>
  <testcase name="documentsPageTest" time="3.189" classname="com.practice.testcases.HomePageTest"/>
  <testcase name="verifyDocumentsPagetitle" time="0.079" classname="com.practice.testcases.HomePageTest"/>
  <testcase name="dashboardPageTest" time="5.371" classname="com.practice.testcases.HomePageTest"/>
  <testcase name="verifyDashboardPageTitle" time="0.047" classname="com.practice.testcases.HomePageTest">
    <failure type="java.lang.AssertionError" message="expected [Administrator - Documents - vtiger CRM 5 - Commercial Open Source CRM] but found [Administrator - Dashboards - vtiger CRM 5 - Commercial Open Source CRM]">
      <![CDATA[java.lang.AssertionError: expected [Administrator - Documents - vtiger CRM 5 - Commercial Open Source CRM] but found [Administrator - Dashboards - vtiger CRM 5 - Commercial Open Source CRM]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.practice.testcases.HomePageTest.verifyDashboardPageTitle(HomePageTest.java:145)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyDashboardPageTitle -->
</testsuite> <!-- com.practice.testcases.HomePageTest -->
